### ISSUE TITLE
i cant make this work i am missing something

### ISSUE THREAD

**Issue by cnilsecure** [adam-kabbara/spotify2mp3#1]
python3 ./main.py 
Traceback (most recent call last):
  File "./main.py", line 14, in <module>
    app.secret_key = private.secret_key
AttributeError: module 'private' has no attribute 'secret_key'

Is there a place to put the secret key inside the code?

**Comment by adam-kabbara** [comment]
What I did over here is that I made a Python module/file called private.py containing the secret variables. After that, you can import the private module and access the variables through that.
